#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Association Française du Poêle Maçonné Artisanal
#

rules = [
  OrganizeImports,
  RemoveUnused
]

RemoveUnused {
  imports = true
}

OrganizeImports.groupedImports = Explode
OrganizeImports.expandRelative = true
OrganizeImports.removeUnused = true
OrganizeImports.groups = [
  "re:javax?\\.",
  "scala.",
  "scala.meta.",
  "cats.",
  "algebra.",
  "afpma.firecalc.units",
  "afpma.firecalc.utils",
  "afpma.firecalc.dto",
  "afpma.firecalc.i18n",
  "afpma.firecalc.engine",
  "afpma.firecalc.fdim",
  "afpma.firecalc.labo",
  "afpma.firecalc.reports",
  "afpma.firecalc.invoices",
  "afpma.firecalc.payments",
  "afpma.firecalc.ui.i18n",
  "afpma.firecalc.ui.",
  "\\*",
]
OrganizeImports.targetDialect = Scala3