#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Association Française du Poêle Maçonné Artisanal
#

rules = [
  OrganizeImports,
  RemoveUnused,
  # ExplicitResultTypes,
  DisableSyntax,
  RedundantSyntax
]

RemoveUnused {
  imports = false
  privates = true
  locals = true
  patternvars = true
}

# --- Add explicit types to reduce compiler inference cost ---
# ExplicitResultTypes {
#  fetchScala3CompilerArtifactsOnVersionMismatch = true
#   memberKind = [Def, Val, Var]
#   memberVisibility = [Public, Protected]
#   skipSimpleDefinitions = ['Lit', 'Term.Ref', 'Term.New']
#   fatalWarnings = false
#}

OrganizeImports {
  groupedImports = Explode
  expandRelative = true
  removeUnused = true
  targetDialect = Scala3
  coalesceToWildcardImportThreshold = null
  groupExplicitlyImportedImplicitsSeparately = true
  groups = [
    "re:javax?\\.",
    "algebra.",
    "afpma.firecalc.units",
    "afpma.firecalc.utils",
    "afpma.firecalc.dto",
    "afpma.firecalc.i18n",
    "afpma.firecalc.engine",
    "afpma.firecalc.fdim",
    "afpma.firecalc.labo",
    "afpma.firecalc.reports",
    "afpma.firecalc.invoices",
    "afpma.firecalc.payments",
    "afpma.firecalc.ui.i18n",
    "afpma.firecalc.ui.",
    "cats.",
    "com.raquo.",
    "coulomb.",
    "scala.",
    "\\*",
  ]
}

DisableSyntax {
  noFinalize = true
  regex = [
    # {
    #   id = "coulombutilsWildcardGiven"
    #   pattern = "import\\s+afpma\\.firecalc\\.units\\.coulombutils\\.given"
    #   message = "Avoid wildcard given import for coulombutils. Import specific givens to reduce implicit search cost."
    # }
    # {
    #   id = "catsWildcardGiven"
    #   pattern = "import\\s+cats\\..+\\.given"
    #   message = "Avoid wildcard given import for cats packages. Import specific givens to reduce implicit search scope."
    # }
    # {
    #   id = "catsImplicitsWildcard"
    #   pattern = "import cats\\.implicits\\.\\*"
    #   message = "Use cats.syntax.specific.* instead of cats.implicits.* to reduce implicit search scope"
    # }
  ]
}