'''
SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2026 Association Française du Poêle Maçonné Artisanal
'''

#!/usr/bin/env python3
"""
Scala 3 Compiler Trace Analyzer
================================

Analyzes Chrome Trace Event format files generated by the Scala 3 compiler
profiling options: -Yprofile-enabled -Yprofile-trace:<path>.trace

These trace files can also be opened visually in https://ui.perfetto.dev/

Usage:
    python3 scripts/analyze_compiler_traces.py [trace_file ...]

If no arguments are given, it scans the traces/ directory for *.trace files.

Output:
    For each trace file, prints:
    - Compiler phase durations (typer, inlining, etc.)
    - Top 20 slowest source files
    - Top 15 slowest typecheck items (classes, methods, objects)
    - Top 15 slowest inline expansions

How to generate traces:
    Add to build.sbt scalacOptions:
        "-Yprofile-enabled",
        "-Yprofile-trace:traces/<module-name>.trace"
    Then run: sbt clean compile
"""

import json
import sys
import glob
from collections import defaultdict
from pathlib import Path


def analyze_trace(trace_file: str) -> None:
    """Parse a Scala compiler trace file and print a summary."""
    with open(trace_file) as f:
        data = json.load(f)

    events = data if isinstance(data, list) else data.get("traceEvents", [])

    print(f"\n{'=' * 60}")
    print(f"  {trace_file}")
    print(f"{'=' * 60}")

    total_events = len(events)
    be_events = sum(1 for e in events if e.get("ph") in ("B", "E"))
    x_events = sum(1 for e in events if e.get("ph") == "X")
    print(f"Total events: {total_events} (B/E pairs: {be_events // 2}, complete: {x_events})")

    # --- Phase durations ---
    phase_stack: list[tuple[str, int]] = []
    phase_durations: dict[str, float] = {}
    for e in events:
        if e.get("cat") == "phase":
            if e["ph"] == "B":
                phase_stack.append((e["name"], e["ts"]))
            elif e["ph"] == "E" and phase_stack:
                name, start = phase_stack.pop()
                dur = (e["ts"] - start) / 1_000_000  # microseconds to seconds
                phase_durations[name] = phase_durations.get(name, 0) + dur

    total_phase_s = sum(phase_durations.values())
    print(f"\nCompiler phase durations (total: {total_phase_s:.1f}s):")
    for name, dur in sorted(phase_durations.items(), key=lambda x: -x[1]):
        pct = dur / total_phase_s * 100 if total_phase_s else 0
        print(f"  {dur:8.1f}s  ({pct:4.1f}%)  {name}")

    # --- File durations ---
    file_stack: list[tuple[str, int]] = []
    file_durations: dict[str, float] = defaultdict(float)
    for e in events:
        if e.get("cat") == "file":
            if e["ph"] == "B":
                file_stack.append((e.get("name", ""), e["ts"]))
            elif e["ph"] == "E" and file_stack:
                name, start = file_stack.pop()
                dur = (e["ts"] - start) / 1_000  # microseconds to ms
                if name:
                    file_durations[name] += dur

    print(f"\nTop 20 slowest files (ms):")
    for name, dur in sorted(file_durations.items(), key=lambda x: -x[1])[:20]:
        print(f"  {dur:8.0f}ms  {name}")

    # --- Typecheck durations ---
    tc_stack: list[tuple[str, int]] = []
    tc_durations: dict[str, float] = defaultdict(float)
    for e in events:
        if e.get("cat") == "typecheck":
            if e["ph"] == "B":
                tc_stack.append((e.get("name", ""), e["ts"]))
            elif e["ph"] == "E" and tc_stack:
                name, start = tc_stack.pop()
                dur = (e["ts"] - start) / 1_000
                if name:
                    tc_durations[name] += dur

    print(f"\nTop 15 slowest typechecks (ms):")
    for name, dur in sorted(tc_durations.items(), key=lambda x: -x[1])[:15]:
        print(f"  {dur:8.0f}ms  {name[:100]}")

    # --- Inline durations ---
    inline_stack: list[tuple[str, int]] = []
    inline_durations: dict[str, float] = defaultdict(float)
    for e in events:
        if e.get("cat") == "inline":
            if e["ph"] == "B":
                inline_stack.append((e.get("name", ""), e["ts"]))
            elif e["ph"] == "E" and inline_stack:
                name, start = inline_stack.pop()
                dur = (e["ts"] - start) / 1_000
                if name:
                    inline_durations[name] += dur

    if inline_durations:
        total_inline_ms = sum(inline_durations.values())
        print(f"\nTop 15 slowest inlines (total: {total_inline_ms / 1000:.1f}s):")
        for name, dur in sorted(inline_durations.items(), key=lambda x: -x[1])[:15]:
            print(f"  {dur:8.0f}ms  {name[:100]}")

    # --- Implicit resolution durations ---
    impl_stack: list[tuple[str, int]] = []
    impl_durations: dict[str, float] = defaultdict(float)
    for e in events:
        if e.get("cat") == "implicit":
            if e["ph"] == "B":
                impl_stack.append((e.get("name", ""), e["ts"]))
            elif e["ph"] == "E" and impl_stack:
                name, start = impl_stack.pop()
                dur = (e["ts"] - start) / 1_000
                if name:
                    impl_durations[name] += dur

    if impl_durations:
        total_impl_ms = sum(impl_durations.values())
        print(f"\nTop 15 slowest implicit resolutions (total: {total_impl_ms / 1000:.1f}s):")
        for name, dur in sorted(impl_durations.items(), key=lambda x: -x[1])[:15]:
            print(f"  {dur:8.0f}ms  {name[:100]}")


def main() -> None:
    if len(sys.argv) > 1:
        trace_files = sys.argv[1:]
    else:
        trace_files = sorted(glob.glob("traces/*.trace"))

    if not trace_files:
        print("No trace files found. Run with trace file paths or place them in traces/")
        sys.exit(1)

    for tf in trace_files:
        analyze_trace(tf)


if __name__ == "__main__":
    main()
